//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA_PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projrequest
    {
        public int Id { get; set; }
        public int projectid { get; set; }
        public int progressid { get; set; }
    
        public virtual progress progress { get; set; }
        public virtual project project { get; set; }
    }
}
