//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA_PM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string descreption { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<double> price { get; set; }
        public int MD { get; set; }
        public int MTL { get; set; }
        public int MT { get; set; }
        public int Customer { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
    }
}
